# Generated by Django 5.2.8 on 2025-11-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Автора'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
    ]
